# Introduction

<img src="https://i.imgur.com/f7DwDnV.jpg" width="500px">

I made this kernel for Kaggle's Digit Recognition competition. In this kernel, given images of handwritten digits, I tried to identify which digit it is.

# Contents

* Preliminary steps
    * Importing the necessary libraries
    * Converting the CSV file into a pandas dataframe
* Defining the features and prediction target
* Creating the model
* Fitting the model
* Dealing with the test data
* Identifying the digit
* Ending Note

Importing the necessary libraries -

In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import numpy as np
import pandas as pd
from tqdm.notebook import tqdm

import keras
from keras.models import Sequential
from keras.layers import Dense, Input
from keras.utils import to_categorical

tqdm.pandas()
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

/kaggle/input/digit-recognizer/sample_submission.csv
/kaggle/input/digit-recognizer/test.csv
/kaggle/input/digit-recognizer/train.csv

Using TensorFlow backend.
/opt/conda/lib/python3.7/site-packages/tqdm/std.py:658: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel

Converting the CSV file into a pandas dataframe -

In [2]:
train_path = '../input/digit-recognizer/train.csv'
train_data = pd.read_csv(train_path)
train_data = train_data.fillna(train_data.mean())

A look at some of the train data -

In [3]:
train_data.head(10)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Defining the features and prediction target -

Defining the features and prediction target, converting the dataframe into a numpy array and bringing all the features to a range between 0 and 1 by dividing all the values of a feature by its biggest value (255) -

In [4]:
y = to_categorical(train_data["label"].values)
X = train_data[train_data.columns[1:]].values/255

Splitting the training data into training data and validation data -

In [5]:
train_X, val_X, train_y, val_y = train_test_split(X, y)

### Creating the model

In [6]:
model = Sequential()
model.add(Dense(units=20, activation='relu'))
model.add(Dense(units=15, activation='relu'))
model.add(Dense(units=10, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

Providing the input size to the model -

In [7]:
model.build(input_shape=(None, 784))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 20)                15700
_________________________________________________________________
dense_2 (Dense)              (None, 15)                315
_________________________________________________________________
dense_3 (Dense)              (None, 10)                160
=================================================================
Total params: 16,175
Trainable params: 16,175
Non-trainable params: 0
_________________________________________________________________

### Fitting the model

In [8]:
model.fit(x=train_X, y=train_y, validation_data=(val_X, val_y), epochs=10)

Train on 31500 samples, validate on 10500 samples
Epoch 1/10
31500/31500 [==============================] - 2s 65us/step - loss: 0.5377 - acc: 0.8444 - val_loss: 0.2789 - val_acc: 0.9210
Epoch 2/10
31500/31500 [==============================] - 2s 60us/step - loss: 0.2693 - acc: 0.9241 - val_loss: 0.2354 - val_acc: 0.9340
Epoch 3/10
31500/31500 [==============================] - 2s 59us/step - loss: 0.2256 - acc: 0.9361 - val_loss: 0.2054 - val_acc: 0.9415
Epoch 4/10
31500/31500 [==============================] - 2s 57us/step - loss: 0.1957 - acc: 0.9446 - val_loss: 0.2092 - val_acc: 0.9374
Epoch 5/10
31500/31500 [==============================] - 2s 58us/step - loss: 0.1756 - acc: 0.9501 - val_loss: 0.1904 - val_acc: 0.9449
Epoch 6/10
31500/31500 [==============================] - 2s 57us/step - loss: 0.1588 - acc: 0.9554 - val_loss: 0.1697 - val_acc: 0.9504
Epoch 7/10
31500/31500 [==============================] - 2s 57us/step - loss: 0.1460 - acc: 0.9590 - val_loss: 0.1655 - val_acc: 0.9516
Epoch 8/10
31500/31500 [==============================] - 2s 60us/step - loss: 0.1344 - acc: 0.9617 - val_loss: 0.1650 - val_acc: 0.9513
Epoch 9/10
31500/31500 [==============================] - 2s 60us/step - loss: 0.1242 - acc: 0.9648 - val_loss: 0.1648 - val_acc: 0.9499
Epoch 10/10
31500/31500 [==============================] - 2s 61us/step - loss: 0.1182 - acc: 0.9658 - val_loss: 0.1608 - val_acc: 0.9524

### Dealing with the test data

Converting the CSV file holding the test data into a pandas dataframe -

In [9]:
test_path = '../input/digit-recognizer/test.csv'
test_data = pd.read_csv(test_path)
test_data = test_data.fillna(test_data.mean())

A look at the test data -

In [10]:
test_data.head(10)

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Defining a new variable to hold the features, converting the dataframe into a numpy array and bringing all the features to a range between 0 and 1 by dividing all the values of a feature by its biggest value (255) -

In [11]:
X_test = test_data[test_data.columns].values/255

### Identifying the digit

In [12]:
predictions = model.predict(X_test)
predictions = np.argmax(predictions, axis=1)

Since sample_submission.csv is of the format in which our submission is supposed to be made, I'm first importing it and converting it into a pandas dataframe -

In [13]:
path = '../input/digit-recognizer/sample_submission.csv'
submission = pd.read_csv(path)

A look at sample_submission.csv -

In [14]:
submission.head(10)

   ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0
5        6      0
6        7      0
7        8      0
8        9      0
9       10      0

Replacing the 'Label' column in the dataframe with the values we got -

In [15]:
submission["Label"] = np.int32(predictions)

A final look at the dataframe with our predictions -

In [16]:
submission.head(10)

   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      4
4        5      3
5        6      7
6        7      0
7        8      3
8        9      0
9       10      3

Converting the dataframe into a csv file without the index column -

In [17]:
submission.to_csv('submission.csv', index=False)

## Ending Note

Through this project, I learnt about a few more activation functions like softmax. I really enjoyed it, and look forward to learning more in the future. This being only my second ml model, I really appreciate feedback to help me improve both the accuracy and efficiency of my model :)